language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe --allow-redirect 
  - awesome_bot -f content/about.md, content/contact.md, content/projects.md  --allow-dupe --allow-redirect --white-list https://www.linkedin.com/