language: ruby
rvm:
  - 3.0
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe --allow-redirect
  - awesome_bot content/*.md  --allow-dupe --allow-redirect --white-list https://www.linkedin.com/
  - awesome_bot content/post/*.md --allow-dupe --allow-redirect 
