language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe --allow-redirect 
  - awesome_bot content/*.md  --allow-dupe --allow-redirect --white-list https://www.linkedin.com/
  - awesome_bot post/*.md --allow-dupe --allow-redirect 