# hostname (and path) to the root eg. http://google.com/
baseurl = "https://therishabh.in/"

publishDir = "public"

DefaultContentLanguage = "en"

# Language
languageCode = "en"

# SES friendly url:s
canonifyurls = true

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-bootstrap-premium"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "rishabh0402"

[permalinks]
    #post = "/:year/:month/:day/:filename/"
    post = "/:filename/"
    code = "/:filename/"

[taxonomies]
    Tag = "tags"
    Topic = "topics"

[author]
    name = "Rishabh"
    email = "hello@therishabh.in"

#
# All parameters below here are optional and can be mixed and matched.
#

[params]
  # bootswatch theme name, select one: cerulean, cosmo (+2:me), cyborg, darkly,
  # default, flatly, journal,  lumen, paper, readable, sandstone, simplex,
  # slate, spacelab, superhero, united, yeti(+2:me).

  bootswatchtheme = "cosmo"

  # menu for changing language. This changes languages with js and stores the choice with the help
  # of JavaScript in a Cookie. Then the path is rewritten with pathnamereplace.js. The name of the
  # md files needs to have the same name for each language abbreviation to work correctly. Example:
  # showcase.en.md and showcase.sv.md. It only works if DefaultContentLanguageInSubdir = true
  switchlang = false

  # You can use markdown here.
  BrandImage = "/logo.png" #top header brand image.
  brand = "Rishabh" # brand image alt text.
  topline = "Research Scholar | Software Engineer"
  footline = "Made with <i style='color:red' class='fa fa-heart'></i>"

  # Show a sidebar menu
  showRightSidebar = true

  # Text for the top menu link, which goes the root URL for the site.
  # Default (if omitted) is "Home".
  home = "Home"

  # Select a syntax highight.
  # Check the static/css/highlight directory for options.
  highlight = "monokai"

  # Google Analytics.
  googleAnalytics = "UA-69202678-3"

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = true
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

    # Menus
    # If you want active menu items highlighted for internal pages don't add them here, they need to be added in each files front matter.
    # like this:
    #[menu]
    #     [menu.main]
    #        name = "Showcase"
    #        weight = 3
    #        identifier = "showcase"
    # i18n menus. A menu will be added for each language to the right in the top menu. This menu will switch to the selected language. Remember to add the corresponding language in pathnamereplace.js.
    #[[Languages.sv.menu.switchlang]]
    #  name = "English"
    #  identifier = ""
    #  weight = 4
    #  url = "en"

    [Languages]
    [Languages.en]
    weight = 1
    copyright = "(c) : 2022 | Rishabh"
    title = "Rishabh's Website" # Site title

    [[Languages.en.menu.main]]
    name = "About"
    weight = 1
    identifier = "about"
    url = "/about"

    [[Languages.en.menu.main]]
    name = "Contact"
    identifier = "contact"
    weight = 2
    url = "/contact"

    [[Languages.en.menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 3
    url = "/projects"

    [[Languages.en.menu.main]]
    name = "Blog"
    identifier = "post"
    weight = 4
    url = "/post"

    [[Languages.en.menu.main]]
    name = "TIL"
    identifier = "today-i-learned"
    weight = 5
    url = "/today-i-learned"
