name = "Hugoplate"
license = "CC BY-NC-ND 4.0"
licenselink = "https://github.com/Rishabh04-02/Rishabh04-02/blob/main/LICENSE.md"
description = "Rishabh's website"
homepage = "https://therishabh.in"
min_version = "0.141.0"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "Rishabh"
homepage = "https://therishabh.in"

[original]
author = "Rishabh"
homepage = "https://therishabh.in"
repo = "https://github.com/Rishabh04-02/Rishabh04-02"
